import { useState } from 'react'

export default function MessageList ({
}) {


  return (
        <div className='w-full h-full overflow-y-auto overscroll-none'>
        Message 
        Message 
        Message 
        Message 
        Message 
        Message 
        Message 
        Message 
        Message 
        Message 
        Message 
        Message 
        Message 
        Message 
        Message 
        Message 
        Message 
        Message 
        Message 
        Message 
        Message 
        Message 
        Message 
        Message 
        Message 
        Message 
        Message 
        Message 
        Message 
        Message 
        Message 
        Message 
        Message 
        Message 
        Message 
        Message 
        Message 
        Message 
        Message 
        Message 
        Message 
        Message 
        Message 
        Message 
        Message 
        Message 
        Message 
        Message 
        Message 
        Message 
        Message 
        Message 
        Message 
        Message 
        Message 
        Message 
        Message 
        Message 
        Message 
        Message 
        Message 
        Message 
        Message 
        Message 
        Message 
        Message 
        Message 
        Message 
        Message 
        Message 
        Message 
        Message 
        Message 
        Message 
        Message 
        Message 
        Message 
        Message 
        Message 
        Message 
        Message 
        Message 
        Message 
        Message 
        Message 
        Message 
        Message 
        Message 
        Message 
        Message 
        Message 
        Message 
        Message 
        Message 
        Message 
        Message 
        Message 
        Message 
        Message 
        Message 
        Message 
        Message 
        Message 
        Message 
        Message 
        Message 
        Message 
        Message 
        Message 
        Message 


    </div>
  )
}
